version: "3.9"

services:
  api:
    image: python:3.12-slim
    working_dir: /app
    env_file: .env
    environment:
      TZ: Europe/Copenhagen
    volumes:
      - ./backend:/app
      - ./data:/data
    command: ["sh","-lc","pip install --no-cache-dir fastapi uvicorn[standard] sqlmodel passlib[bcrypt] PyJWT python-multipart && uvicorn main:app --host 0.0.0.0 --port 8000"]
 

  web:
    image: caddy:alpine
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"          # <- VIGTIG
    volumes:
      - ./frontend:/usr/share/caddy:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-data:/data          # <- persister certs
      - ./caddy-config:/config
    environment:
      - TZ=Europe/Copenhagen
