version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    environment:
      TZ: Europe/Copenhagen
    volumes:
      - ./data:/data
    restart: unless-stopped
 

  web:
    image: caddy:alpine
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"          # <- VIGTIG
    volumes:
      - ./frontend:/usr/share/caddy:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-data:/data          # <- persister certs
      - ./caddy-config:/config
    environment:
      - TZ=Europe/Copenhagen
